package com.huofu.module.i5wei.base;

/**
 * 缓存前缀
 * Created by akwei on 5/18/16.
 */
public interface I5weiCachePrefix {

    String REFRESH_SIGN_IN_APPCOPY = "1.0";

    String STORE_PROMOTION_SUB_VERSION = "2";

    String STORE_PROMOTION_REBATE = "2." + STORE_PROMOTION_SUB_VERSION;

    String STORE_PROMOTION_REBATE_PERIODS = "3." + STORE_PROMOTION_SUB_VERSION;

    String STORE_PROMOTION_REBATE_CHARGE_ITEMS = "4." + STORE_PROMOTION_SUB_VERSION;

    String STORE_PROMOTION_REDUCE = "5." + STORE_PROMOTION_SUB_VERSION;

    String STORE_PROMOTION_REDUCE_PERIODS = "6." + STORE_PROMOTION_SUB_VERSION;

    String STORE_PROMOTION_REDUCE_CHARGE_ITEMS = "7." + STORE_PROMOTION_SUB_VERSION;

    String STORE_PROMOTION_REDUCE_QUOTA = "8." + STORE_PROMOTION_SUB_VERSION;

    String STORE_PRODUCT = "9.0";

    String STORE_CHARGE_ITEM = "10.0";

    String STORE_TIME_BUCKET = "11.0";

    String STORE_SUB_CHARGE_ITEM = "12.0";
    
    String STORE_PROMOTION_GRATIS = "13." + STORE_PROMOTION_SUB_VERSION;
    
    String STORE_PROMOTION_GRATIS_CHARGE_ITEMS="14.1";
    
    String  STORE_PROMOTION_GRATIS_PERIODS="15."+STORE_PROMOTION_SUB_VERSION; 
  
}
